from __future__ import annotations

import re


DISALLOWED_IMPORT_ROOTS = {
    "asyncio",
    "ctypes",
    "dataclasses",
    "ftplib",
    "http",
    "paramiko",
    "pathlib",
    "requests",
    "shutil",
    "socket",
    "subprocess",
    "urllib",
    "urllib2",
    "winreg",
    "_winreg",
}
DISALLOWED_CALLS = {"__import__", "compile", "eval", "exec", "input", "raw_input"}
DISALLOWED_ATTR_CALLS = {
    ("os", "fspath"),
    ("os", "popen"),
    ("os", "remove"),
    ("os", "removedirs"),
    ("os", "rename"),
    ("os", "replace"),
    ("os", "rmdir"),
    ("os", "scandir"),
    ("os", "startfile"),
    ("os", "system"),
    ("os", "unlink"),
}
EXECUTOR_ENCODING_HEADER = "# -*- coding: utf-8 -*-\n"
CODING_RE = re.compile(r"coding[:=]\s*([-\w.]+)")
PYTHON2_UNSUPPORTED_NODE_NAMES = {
    "AnnAssign",
    "AsyncFor",
    "AsyncFunctionDef",
    "AsyncWith",
    "Await",
    "FormattedValue",
    "JoinedStr",
    "Nonlocal",
    "NamedExpr",
}
PYTHON2_UNSUPPORTED_NAMES = {
    "BaseExceptionGroup",
    "BlockingIOError",
    "BrokenPipeError",
    "ChildProcessError",
    "ConnectionError",
    "ExceptionGroup",
    "FileExistsError",
    "FileNotFoundError",
    "InterruptedError",
    "IsADirectoryError",
    "ModuleNotFoundError",
    "NotADirectoryError",
    "PermissionError",
    "ProcessLookupError",
    "StopAsyncIteration",
    "TimeoutError",
}
PYTHON2_UNSUPPORTED_KEYWORDS = {"exist_ok"}
ALLOWED_BARE_CALLS = {
    "Exception",
    "RuntimeError",
    "ValueError",
    "TypeError",
    "KeyError",
    "IndexError",
    "AttributeError",
    "NotImplementedError",
    "ArithmeticError",
    "ZeroDivisionError",
    "abs",
    "all",
    "any",
    "bool",
    "basestring",
    "chr",
    "dict",
    "enumerate",
    "filter",
    "float",
    "format",
    "getattr",
    "hasattr",
    "int",
    "isinstance",
    "iter",
    "len",
    "list",
    "long",
    "map",
    "max",
    "min",
    "next",
    "ord",
    "open",
    "range",
    "repr",
    "reversed",
    "round",
    "set",
    "setattr",
    "slice",
    "sorted",
    "str",
    "sum",
    "tuple",
    "unicode",
    "unichr",
    "xrange",
    "zip",
}
ALLOWED_ARCPY_CALLS = {
    ("arcpy", "AddFieldDelimiters"),
    ("arcpy", "AddField_management"),
    ("arcpy", "Append_management"),
    ("arcpy", "Array"),
    ("arcpy", "Buffer_analysis"),
    ("arcpy", "Clip_analysis"),
    ("arcpy", "CopyRaster_management"),
    ("arcpy", "CopyFeatures_management"),
    ("arcpy", "CreateFeatureclass_management"),
    ("arcpy", "CreateFileGDB_management"),
    ("arcpy", "DeleteField_management"),
    ("arcpy", "Delete_management"),
    ("arcpy", "Describe"),
    ("arcpy", "Dissolve_management"),
    ("arcpy", "Erase_analysis"),
    ("arcpy", "Exists"),
    ("arcpy", "FeatureToPoint_management"),
    ("arcpy", "GetCount_management"),
    ("arcpy", "Geometry"),
    ("arcpy", "Identity_analysis"),
    ("arcpy", "Intersect_analysis"),
    ("arcpy", "ListFields"),
    ("arcpy", "MakeFeatureLayer_management"),
    ("arcpy", "Merge_management"),
    ("arcpy", "Multipoint"),
    ("arcpy", "Point"),
    ("arcpy", "PointGeometry"),
    ("arcpy", "Polygon"),
    ("arcpy", "Polyline"),
    ("arcpy", "Project_management"),
    ("arcpy", "SelectLayerByAttribute_management"),
    ("arcpy", "SelectLayerByLocation_management"),
    ("arcpy", "SpatialJoin_analysis"),
    ("arcpy", "SpatialReference"),
    ("arcpy", "SymDiff_analysis"),
    ("arcpy", "Union_analysis"),
    ("arcpy", "Update_analysis"),
    ("arcpy", "da", "InsertCursor"),
    ("arcpy", "da", "SearchCursor"),
    ("arcpy", "da", "UpdateCursor"),
    ("arcpy", "management", "AddField"),
    ("arcpy", "management", "CopyFeatures"),
    ("arcpy", "management", "CopyRaster"),
    ("arcpy", "management", "CreateFeatureclass"),
    ("arcpy", "management", "CreateFileGDB"),
    ("arcpy", "management", "Delete"),
    ("arcpy", "management", "GetCount"),
    ("arcpy", "management", "MakeFeatureLayer"),
}
RESERVED_ARCGIS_FIELD_NAMES = {
    "fid",
    "objectid",
    "oid",
    "shape",
    "shape_area",
    "shape_length",
}
RESERVED_CURSOR_WRITE_FIELDS = RESERVED_ARCGIS_FIELD_NAMES | {"oid@"}
